### ISSUE TITLE
STAC API Client

### ISSUE THREAD

**Issue by brentfraser** [Terradue/DotNetStac#1]
I see in the Notebook you mention a "feature to come" of STAC API Client.  Has there been any work on this?

**Comment by fabricebrito** [comment]
Hello @brentfraser, we've been busy adding several EO missions 
I'm afraid there hasn't been much work on the STAC API client.
Is there a particular feature you'd like to have?

**Comment by brentfraser** [comment]
Nothing particular right now.  I've been tasked with doing maintenance on a DotNet application based on the [DotSpatial ](https://github.com/DotSpatial/DotSpatial) library.  STAC might be useful in giving the user the ability to find imagery on the Internet.

**Comment by emmanuelmathot** [comment]
We are preparing a version to align with the release 1.0.0 of STAC. DotNetStac shall focus only on the STAC spec. Another library under development will propose a full STAC API client.

**Comment by brentfraser** [comment]
That's great!  Thanks!
