### ISSUE TITLE
Add user-specified headers to WebClient

### ISSUE THREAD

**Issue by brentfraser** [Terradue/DotNetStac#4]
Some Stac servers may require authentication.  I have a Stac server that takes a username+password and returns an authorization token string.  I'd like to add it to the WebClient object before a request for the catalog is made. 

So in [StacFactory ](https://github.com/Terradue/DotNetStac/blob/f62b59941525e31b30ddb73d89cb744eff6fe221/src/DotNetStac/StacFactory.cs#L16), something like:

```
WebClient client = new WebClient();
client.Headers.Add("Authorization", token);
return await client.DownloadStringTaskAsync(uri)...
```

or some generalized method of adding Headers.

**Comment by emmanuelmathot** [comment]
We are preparing a version to align with the release 1.0.0 of STAC. This library will be data middleware agnostic. We will remove all loaders to leave this part entirely to the developer. DotNetStac shall focus only on the STAC spec. Another library (https://github.com/Terradue/Stars), more as an SDK, will propose many helpers (with loaders) to navigate properly through the STAC documents.

**Comment by brentfraser** [comment]
Thanks!
